problemType:
  url: http://localhost:8080
spring:
  datasource:
    password: root
    url: jdbc:h2:file:./data/sigabem_DB
    username: root
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: true
